/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiNotifyRouteImport } from './routes/api.notify'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as ApiPublicRoomsRouteImport } from './routes/api.public.rooms'
import { Route as ApiPublicBookingsRouteImport } from './routes/api.public.bookings'
import { Route as ApiMpesaStkRouteImport } from './routes/api.mpesa.stk'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api.mpesa.callback'
import { Route as ApiPublicMpesaStkRouteImport } from './routes/api.public.mpesa.stk'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiNotifyRoute = ApiNotifyRouteImport.update({
  id: '/api/notify',
  path: '/api/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicRoomsRoute = ApiPublicRoomsRouteImport.update({
  id: '/api/public/rooms',
  path: '/api/public/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStkRoute = ApiMpesaStkRouteImport.update({
  id: '/api/mpesa/stk',
  path: '/api/mpesa/stk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaStkRoute = ApiPublicMpesaStkRouteImport.update({
  id: '/api/public/mpesa/stk',
  path: '/api/public/mpesa/stk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/notify': typeof ApiNotifyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/stk': typeof ApiMpesaStkRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/rooms': typeof ApiPublicRoomsRoute
  '/api/public/mpesa/stk': typeof ApiPublicMpesaStkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/notify': typeof ApiNotifyRoute
  '/admin': typeof AdminIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/stk': typeof ApiMpesaStkRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/rooms': typeof ApiPublicRoomsRoute
  '/api/public/mpesa/stk': typeof ApiPublicMpesaStkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/notify': typeof ApiNotifyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/stk': typeof ApiMpesaStkRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/rooms': typeof ApiPublicRoomsRoute
  '/api/public/mpesa/stk': typeof ApiPublicMpesaStkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/signup'
    | '/admin/staff'
    | '/api/notify'
    | '/admin/'
    | '/api/mpesa/callback'
    | '/api/mpesa/stk'
    | '/api/public/bookings'
    | '/api/public/rooms'
    | '/api/public/mpesa/stk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/signup'
    | '/admin/staff'
    | '/api/notify'
    | '/admin'
    | '/api/mpesa/callback'
    | '/api/mpesa/stk'
    | '/api/public/bookings'
    | '/api/public/rooms'
    | '/api/public/mpesa/stk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/signup'
    | '/admin/staff'
    | '/api/notify'
    | '/admin/'
    | '/api/mpesa/callback'
    | '/api/mpesa/stk'
    | '/api/public/bookings'
    | '/api/public/rooms'
    | '/api/public/mpesa/stk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiNotifyRoute: typeof ApiNotifyRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiMpesaStkRoute: typeof ApiMpesaStkRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicRoomsRoute: typeof ApiPublicRoomsRoute
  ApiPublicMpesaStkRoute: typeof ApiPublicMpesaStkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/notify': {
      id: '/api/notify'
      path: '/api/notify'
      fullPath: '/api/notify'
      preLoaderRoute: typeof ApiNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/rooms': {
      id: '/api/public/rooms'
      path: '/api/public/rooms'
      fullPath: '/api/public/rooms'
      preLoaderRoute: typeof ApiPublicRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/stk': {
      id: '/api/mpesa/stk'
      path: '/api/mpesa/stk'
      fullPath: '/api/mpesa/stk'
      preLoaderRoute: typeof ApiMpesaStkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/stk': {
      id: '/api/public/mpesa/stk'
      path: '/api/public/mpesa/stk'
      fullPath: '/api/public/mpesa/stk'
      preLoaderRoute: typeof ApiPublicMpesaStkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiNotifyRoute: ApiNotifyRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiMpesaStkRoute: ApiMpesaStkRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicRoomsRoute: ApiPublicRoomsRoute,
  ApiPublicMpesaStkRoute: ApiPublicMpesaStkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
